-- MySQL Script generated by MySQL Workbench
-- Sat May 20 06:43:06 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Owner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Owner` (
  `Id` INT NOT NULL,
  `Name` VARCHAR(50) NULL,
  `Phone` VARCHAR(15) NULL,
  `Email` VARCHAR(50) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Restaurant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Restaurant` (
  `Id` INT NOT NULL,
  `Name` VARCHAR(50) NULL,
  `Phone` VARCHAR(15) NULL,
  `Email` VARCHAR(50) NULL,
  `Address` VARCHAR(50) NULL,
  `OwnerId` INT NULL,
  PRIMARY KEY (`Id`),
  INDEX `OwnerId_idx` (`OwnerId` ASC) VISIBLE,
  CONSTRAINT `OwnerId`
    FOREIGN KEY (`OwnerId`)
    REFERENCES `mydb`.`Owner` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Menu` (
  `Id` INT NOT NULL,
  `Name` VARCHAR(50) NULL,
  `Description` VARCHAR(100) NULL,
  `RestaurantId` INT NULL,
  PRIMARY KEY (`Id`),
  INDEX `RestaurantId_idx` (`RestaurantId` ASC) VISIBLE,
  CONSTRAINT `RestaurantId`
    FOREIGN KEY (`RestaurantId`)
    REFERENCES `mydb`.`Restaurant` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dish`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dish` (
  `Id` INT NOT NULL,
  `Name` VARCHAR(50) NULL,
  `Description` VARCHAR(100) NULL,
  `Price` INT NULL,
  `Ingredients` VARCHAR(200) NULL,
  `SpicyLevel` VARCHAR(25) NULL,
  `MenuId` INT NULL,
  PRIMARY KEY (`Id`),
  INDEX `MenuId_idx` (`MenuId` ASC) VISIBLE,
  CONSTRAINT `MenuId`
    FOREIGN KEY (`MenuId`)
    REFERENCES `mydb`.`Menu` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Table` (
  `Id` INT NOT NULL,
  `Number` INT NULL,
  `Capacity` INT NULL,
  `RestaurantId` INT NULL,
  PRIMARY KEY (`Id`),
  INDEX `RestaurantId_idx` (`RestaurantId` ASC) VISIBLE,
  CONSTRAINT `RestaurantId`
    FOREIGN KEY (`RestaurantId`)
    REFERENCES `mydb`.`Restaurant` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `Id` INT NOT NULL,
  `Name` VARCHAR(50) NULL,
  `Phone` VARCHAR(15) NULL,
  `Email` VARCHAR(50) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reservation` (
  `Id` INT NOT NULL,
  `TableId` INT NULL,
  `CustomerId` INT NULL,
  `Date` DATE NULL,
  `Time` TIME NULL,
  PRIMARY KEY (`Id`),
  INDEX `TableId_idx` (`TableId` ASC) VISIBLE,
  INDEX `CustomerId_idx` (`CustomerId` ASC) VISIBLE,
  CONSTRAINT `TableId`
    FOREIGN KEY (`TableId`)
    REFERENCES `mydb`.`Table` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CustomerId`
    FOREIGN KEY (`CustomerId`)
    REFERENCES `mydb`.`Customer` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `Id` INT NOT NULL,
  `Name` VARCHAR(50) NULL,
  `Phone` VARCHAR(15) NULL,
  `Email` VARCHAR(50) NULL,
  `Designation` VARCHAR(50) NULL,
  `Salary` INT NULL,
  `Address` VARCHAR(50) NULL,
  `RestaurantId` INT NULL,
  PRIMARY KEY (`Id`),
  INDEX `RestaurantId_idx` (`RestaurantId` ASC) VISIBLE,
  CONSTRAINT `RestaurantId`
    FOREIGN KEY (`RestaurantId`)
    REFERENCES `mydb`.`Restaurant` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Order` (
  `Id` INT NOT NULL,
  `TableId` INT NULL,
  `EmployeeId` INT NULL,
  `DATE` DATE NULL,
  `Amount` INT NULL,
  PRIMARY KEY (`Id`),
  INDEX `EmployeeId_idx` (`EmployeeId` ASC) VISIBLE,
  INDEX `TableId_idx` (`TableId` ASC) VISIBLE,
  CONSTRAINT `TableId`
    FOREIGN KEY (`TableId`)
    REFERENCES `mydb`.`Table` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `EmployeeId`
    FOREIGN KEY (`EmployeeId`)
    REFERENCES `mydb`.`Employee` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
